finish some of any and do some code formatting
covscript/new-covscript pull request #4
Opened 2019-09-19 16:40 UTC by mikecovlee

Well, our any now can run fast with small object optimize

2019-09-19 17:06 UTC, ice1000 reviewed
As a formatting PR, why both `a = b` and `a=b` are kept? Do we add spaces around assignment operators or don't we?

2019-09-19 17:06 UTC, ice1000 commented on shared/include/covscript/shared/any.hpp
> +	struct stor_union {
What does "stor" stand for?

2019-09-19 23:18 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
> +	struct stor_union {
Storage I think.

2019-09-19 23:26 UTC, imkiva requested changes
Spaces. Spaces. Spaces.....
Please just keep that in mind.....
I have been saying that for 3 thousand times.........

2019-09-19 23:26 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
> -    using typeid_t=std::type_index;
Please just add some spaces around `=`

2019-09-19 23:26 UTC, imkiva commented on shared/include/covscript/shared/exception.hpp
> -        std::exception &stdexcept=exception;
Spaces here pls :)

2019-09-19 23:26 UTC, imkiva commented on shared/include/covscript/shared/exception.hpp
> +		std::exception &stdexcept=exception;
And here....

2019-09-19 23:26 UTC, imkiva commented on shared/src/test_any.cpp
> +	std::cout<<c.get<std::string>()<<std::endl;
PLS add some spaces around `<<`

2019-09-20 00:10 UTC, ice1000 commented
Sticky spaces

2019-09-20 04:39 UTC, imkiva commented
Sticky sapces

2019-09-20 05:01 UTC, merged

2019-09-20 11:59 UTC, imkiva reviewed
Accepted.

2019-09-20 13:21 UTC, ice1000 commented
You should say "approved"

2019-09-20 23:32 UTC, imkiva commented
Well, "Approved" next time.