[compiler-dev] Compiler framework
covscript/new-covscript pull request #7
Opened 2019-09-21 13:13 UTC by imkiva

* Register custom compiler phase
* Phase pipeline

2019-09-21 20:01 UTC, ice1000 reviewed
🚀

2019-09-21 20:01 UTC, ice1000 commented on CMakeLists.txt
> +        compiler/src/covscript/compiler/compiler.cpp compiler/include/covscript/compiler/phase/assembleScan.h compiler/src/covscript/compiler/phase/assembleScan.cpp compiler/include/covscript/compile
Add them to separate lines please.

2019-09-22 13:25 UTC, imkiva commented on CMakeLists.txt
> +        compiler/src/covscript/compiler/compiler.cpp compiler/include/covscript/compiler/phase/assembleScan.h compiler/src/covscript/compiler/phase/assembleScan.cpp compiler/include/covscript/compile
LOL, I forgot.

2019-09-23 09:20 UTC, mikecovlee requested changes
Well lots of problems

2019-09-23 09:20 UTC, mikecovlee commented on compiler/include/covscript/compiler/sharedTypes.h
> +        inline _LIBCPP_INLINE_VISIBILITY
What is it for? I think it is unnecessary.

2019-09-23 09:20 UTC, mikecovlee commented on compiler/include/covscript/compiler/variable.h
> +                return is<const PrimitiveType *>(this);
I don't think it is an efficient way to check types, try using enum class with virtual functions.

2019-09-23 09:20 UTC, mikecovlee commented on compiler/src/covscript/compiler/compiler.cpp
> +                std::rethrow_exception(e);
Remember using cs::throw_ex to throwing an exception.

2019-09-23 09:20 UTC, mikecovlee commented on compiler/src/covscript/compiler/compiler.cpp
> +                throw cs::compiler::SyntaxError(re.getCtx(), offendingSymbol, line, charPositionInLine, msg);
Same as above

2019-09-23 09:20 UTC, mikecovlee commented on compiler/src/covscript/compiler/compiler.cpp
> +            phase->preparePhase(_privateData);
It's dangerous to ignoring the checking of invalid pointer. Remember that std::shared_ptr will still holding nullptr in some cases.

2019-09-23 09:20 UTC, mikecovlee commented on compiler/src/covscript/compiler/parser.cpp
> +                const std::string &ruleName = recognizer->getRuleNames()[recognizer->getContext()->getRuleIndex()];
Dangerous: lack of edge inspection. Using .at instead of operator []

2019-09-23 09:20 UTC, mikecovlee commented on compiler/src/covscript/compiler/phase/assembleDefine.cpp
> +            PHASE_LOG("[Assemble:Define] Enter");
Why not trying to cooperate with COVSDK_LOGXX series macro?

2019-09-23 09:32 UTC, imkiva commented on compiler/include/covscript/compiler/sharedTypes.h
> +        inline _LIBCPP_INLINE_VISIBILITY
To keep my coding style comfortable for me.

2019-09-23 09:33 UTC, mikecovlee commented on compiler/include/covscript/compiler/sharedTypes.h
> +        inline _LIBCPP_INLINE_VISIBILITY
My meaning is the macro `_LIBCPP_INLINE_VISIBILITY`

2019-09-23 09:36 UTC, imkiva commented on compiler/src/covscript/compiler/compiler.cpp
> +            phase->preparePhase(_privateData);
This is a private method and moreover, the Phase instance is created by framework automatically. So there is no need to pay special attention to nullptrs.

2019-09-23 09:37 UTC, imkiva commented on compiler/src/covscript/compiler/compiler.cpp
> +            phase->preparePhase(_privateData);
And, you should use ‘it’s dangerous to ignore’ instead of ‘it’s dangerous to ignoring’

2019-09-23 09:38 UTC, imkiva commented on compiler/src/covscript/compiler/parser.cpp
> +                const std::string &ruleName = recognizer->getRuleNames()[recognizer->getContext()->getRuleIndex()];
ANTLR4 will guarantees that.

2019-09-23 09:40 UTC, mikecovlee commented on compiler/src/covscript/compiler/compiler.cpp
> +            phase->preparePhase(_privateData);
blablablabla, bad english

2019-09-23 09:40 UTC, imkiva commented on compiler/src/covscript/compiler/phase/assembleDefine.cpp
> +            PHASE_LOG("[Assemble:Define] Enter");
See how this macro was defined pls.

2019-09-23 09:41 UTC, mikecovlee commented on compiler/src/covscript/compiler/parser.cpp
> +                const std::string &ruleName = recognizer->getRuleNames()[recognizer->getContext()->getRuleIndex()];
fine

2019-09-23 09:41 UTC, imkiva commented on compiler/include/covscript/compiler/variable.h
> +                return is<const PrimitiveType *>(this);
Next commit will do.

2019-09-23 09:41 UTC, imkiva commented on compiler/src/covscript/compiler/compiler.cpp
> +                std::rethrow_exception(e);
Yeah. I marked it a TODO.

2019-09-23 09:41 UTC, imkiva commented on compiler/src/covscript/compiler/compiler.cpp
> +                throw cs::compiler::SyntaxError(re.getCtx(), offendingSymbol, line, charPositionInLine, msg);
Same as above.

2019-09-23 09:46 UTC, mikecovlee commented
I love github review

2019-09-23 12:46 UTC, ice1000 commented on CMakeLists.txt
> +
fine

2019-09-25 08:21 UTC, mikecovlee reviewed
I think it is ok.

2019-09-25 08:21 UTC, mikecovlee commented on compiler/include/covscript/compiler/variable.h
> +            ~PrimitiveType() override = default;
actually the keyword `override` is not necessary here.

2019-09-25 08:21 UTC, mikecovlee commented on compiler/tests/test-typeflags.cpp
> +    using namespace cs::compiler;
well, using namespace. I hate this, but it is just a testing unit, so, fine.

2019-09-25 08:23 UTC, imkiva commented on compiler/include/covscript/compiler/variable.h
> +            ~PrimitiveType() override = default;
But CLion don't think so.

2019-09-25 08:26 UTC, imkiva commented on compiler/tests/test-typeflags.cpp
> +    using namespace cs::compiler;
Only `using namespace std` is prohibited.
My naming strategy is impossible to contribute to a symbol conflict.

2019-09-25 08:30 UTC, imkiva commented
@mikecovlee `wontfix` is not something meaning `will not be merged`. Please use labels carefully.

2019-09-25 08:31 UTC, imkiva commented
> I think it is ok.

我不要你觉得，我要我觉得，我觉得可以合并了。

2019-09-26 02:23 UTC, mikecovlee approved these changes
🚀

2019-09-26 09:32 UTC, merged