any: performance improvement and bugfix
covscript/new-covscript pull request #9
Opened 2019-09-26 02:29 UTC by mikecovlee

2019-09-26 06:27 UTC, imkiva reviewed
Coding style.

2019-09-26 06:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
> +			throw_ex<runtime_error>("Access null any object.");
Use `cs::runtime_error`. This is quite confusing with `std::runtime_error`.

2019-09-26 06:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
> +			throw_ex<runtime_error>("Access null any object.");
Same as above.

2019-09-26 06:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
>  	* 提示：本框架的Any使用了Small Data Optimize技术，可大幅减少堆的负担
Spaces in comments.

2019-09-26 06:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
>  		// 默认构造函数，使用default实现
Spaces in comments

2019-09-26 06:28 UTC, imkiva requested changes
Coding style.

2019-09-26 07:27 UTC, mikecovlee commented
Finished.

2019-09-26 09:27 UTC, imkiva requested changes
My fault. I didn't review code carefully enough.///

2019-09-26 09:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
> -			throw_ex<runtime_error>("Access null any object.");
`cs::runtime_error`

2019-09-26 09:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
>  			throw_ex<runtime_error>("Access wrong type of any.");
`cs::runtime_error`

2019-09-26 09:27 UTC, imkiva commented on shared/include/covscript/shared/any.hpp
>  			throw_ex<runtime_error>("Access wrong type of any.");
`cs::runtime_error`

2019-09-27 14:25 UTC, mikecovlee commented
Merge master changes and replace all of `runtime_error` to `cs::runtime_error`

2019-09-27 14:34 UTC, merged